# here you can customize every message
messages:
  not_whitelisted: "You're not whitelisted."
  no_longer_whitelisted: "You was just removed from the whitelist and therefore kicked."
  whitelist_now_on: "The whitelist was just turned on. You was kicked because you're not on the whitelist."
  added: "Player '%s' was successfully added to the whitelist"
  already_added: "Player '%s' is already on the whitelist"
  removed: "Player '%s' was successfully removed from the whitelist"
  whitelist_turned_on: "The whitelist was turned on"
  whitelist_turned_off: "The whitelist was turned off"
  whitelist_on: "The whitelist is currently on"
  whitelist_off: "The whitelist is currently off"
  players_on_whitelist: "This player names are whitelisted: %s"
  config_reloaded: "Reloaded UniversalWhitelist config. The whitelist file hasn't been reloaded because it's recommended to use the in-built commands"
