# if the whitelist should be active or not (if you permanently want to disable it, delete the plugin from the server)
activated: true

# customize all messages
messages:
  not_whitelisted: "You're not whitelisted. If you believe this is a mistake, contact the server owner."
  kicked_no_longer_whitelisted: "You have just been removed from the whitelist and therefore kicked"
  uuid_already_added: "UUID '%s' is already added to the whitelist"
  uuid_added: "UUID '%s' has successfully been added to the whitelist"
  uuid_removed: "UUID '%s' has successfully been removed from the whitelist"
  player_already_added: "Player '%s' is already added to the whitelist"
  player_added: "Player '%s' has successfully been added to the whitelist"
  player_removed: "Player '%s' has successfully been removed from the whitelist"
  whitelist_turned_on: "The whitelist has been turned on"
  whitelist_turned_off: "The whitelist has been turned off"
  whitelist_on: "The whitelist is currently on"
  whitelist_off: "The whitelist is currently off"
  players_on_whitelist: "This player names are whitelisted: %s"
  config_reloaded: "Reloaded UniversalWhitelist config. The whitelist file hasn't been reloaded because it's recommended to use the in-built commands"
